export const Identifiers = {
	AppData: "Data<App>",
	Coins: "Coins",
	CoinService: "CoinService",
	ContactRepository: "ContactRepository",
	DataRepository: "DataRepository",
	DelegateService: "DelegateService",
	ExchangeRateService: "ExchangeRateService",
	FeeService: "FeeService",
	HttpClient: "HttpClient",
	KnownWalletService: "KnownWalletService",
	ProfileRepository: "ProfileRepository",
	SettingRepository: "SettingRepository",
	Storage: "Storage",
	WalletRepository: "WalletRepository",
	WalletService: "WalletService",
};
