export const manifest = {
	name: "Lisk",
	ticker: "LSK",
	behaviours: {
		Client: {
			getTransaction: true,
			getTransactions: true,
			searchTransactions: false,
			getWallet: true,
			getWallets: true,
			searchWallets: false,
			getDelegate: true,
			getDelegates: true,
			getConfiguration: false,
			getCryptoConfiguration: false,
			getFeesByNode: false,
			getFeesByType: false,
			getSyncStatus: false,
			postTransactions: true,
		},
		Crypto: {
			createTransfer: true,
			createSecondSignature: true,
			createDelegateRegistration: true,
			createVote: true,
			createMultiSignature: true,
			createIpfs: false,
			createMultiPayment: false,
			createDelegateResignation: false,
			createHtlcLock: false,
			createHtlcClaim: false,
			createHtlcRefund: false,
		},
		Identity: {
			getAddress: {
				passphrase: true,
				multiSignature: false,
				publicKey: true,
				privateKey: false,
				wif: false,
			},
			getPublicKey: {
				passphrase: true,
				multiSignature: false,
				wif: false,
			},
			getPrivateKey: {
				passphrase: true,
				wif: false,
			},
			getWIF: {
				passphrase: false,
			},
			getKeyPair: {
				passphrase: true,
				publicKey: false,
				privateKey: false,
				wif: false,
			},
		},
		Message: {
			sign: true,
			verify: true,
		},
	},
};
