export const manifest = {
	name: "ARK",
	ticker: "ARK",
	behaviours: {
		Client: {
			getBlock: true,
			getBlocks: true,
			searchBlocks: true,
			getTransaction: true,
			getTransactions: true,
			searchTransactions: true,
			getWallet: true,
			getWallets: true,
			searchWallets: true,
			getDelegate: true,
			getDelegates: true,
			getPeers: true,
			getConfiguration: true,
			getCryptoConfiguration: true,
			getFeesByNode: true,
			getFeesByType: true,
			getSyncStatus: true,
			postTransactions: true,
		},
		Crypto: {
			createTransfer: true,
			createSecondSignature: true,
			createDelegateRegistration: true,
			createVote: true,
			createMultiSignature: true,
			createIpfs: true,
			createMultiPayment: true,
			createDelegateResignation: true,
			createHtlcLock: true,
			createHtlcClaim: true,
			createHtlcRefund: true,
		},
		Identity: {
			getAddress: {
				passphrase: true,
				multiSignature: true,
				publicKey: true,
				privateKey: true,
				wif: true,
			},
			getPublicKey: {
				passphrase: true,
				multiSignature: true,
				wif: true,
			},
			getPrivateKey: {
				passphrase: true,
				wif: true,
			},
			getWIF: {
				passphrase: true,
			},
			getKeyPair: {
				passphrase: true,
				publicKey: false,
				privateKey: false,
				wif: true,
			},
		},
		Message: {
			sign: true,
			verify: true,
		},
	},
};
