import { Contracts } from "@arkecosystem/platform-sdk";
import { v4 as uuidv4 } from "uuid";
import { IReadWriteWallet, ITransactionService, WalletData } from "../../../contracts";
import { State } from "../../../environment/state";

import { pqueueSettled } from "../../../helpers/queue";
import { SignedTransactionData } from "./dto/signed-transaction";

type SignedTransactionDataDictionary = Record<string, Contracts.SignedTransactionData>;

/**
 * This class is responsible for managing the state of all transactions that
 * belong to a wallet. This includes signing, broadcasting and confirming.
 *
 * Internally a UUID and transaction ID are used. The UUID is generated by
 * this package and the transaction ID is computed by the coin implementation.
 *
 * The transaction ID can either be created online or offline. Most coins will
 * provide the transaction ID offline but there are exception which will require
 * the transaction to be broadcasted and then return the ID.
 *
 * In such cases the coin implementation will generate a temporary UUID that
 * will be used until the transaction has been broadcasted, at which point
 * we will swap out the UUID for the real transaction ID which we received.
 */
export class TransactionService implements ITransactionService {
	/**
	 * The wallet that all transactions are signed with.
	 *
	 * @memberof TransactionService
	 */
	readonly #wallet: IReadWriteWallet;

	/**
	 * The transactions that have been signed but not necessarily broadcasted.
	 *
	 * @memberof TransactionService
	 */
	#signed: SignedTransactionDataDictionary = {};

	/**
	 * The transactions that have been signed and broadcasted.
	 *
	 * @memberof TransactionService
	 */
	#broadcasted: SignedTransactionDataDictionary = {};

	/**
	 * The transactions that have been signed, broadcasted and confirmed.
	 *
	 * @memberof TransactionService
	 */
	#confirmed: SignedTransactionDataDictionary = {};

	/**
	 * The transactions that are waiting for the signatures of the wallet.
	 *
	 * @memberof TransactionService
	 */
	#waitingForOurSignature: SignedTransactionDataDictionary = {};

	/**
	 * The transactions that are waiting for the signatures of other participants.
	 *
	 * @memberof TransactionService
	 */
	#waitingForOtherSignatures: SignedTransactionDataDictionary = {};

	/**
	 * Creates an instance of TransactionService.
	 *
	 * @param {ReadWriteWallet} wallet
	 * @memberof TransactionService
	 */
	public constructor(wallet: IReadWriteWallet) {
		this.#wallet = wallet;

		this.restore();
	}

	/**
	 * Sync both pending and ready multi signature transactions.
	 *
	 * @returns {Promise<void>}
	 * @memberof TransactionService
	 */
	public async sync(): Promise<void> {
		await pqueueSettled([() => this.syncPendingMultiSignatures(), () => this.syncReadyMultiSignatures()]);
	}

	/**
	 * Sign the transaction for the given ID with the given mnemonic.
	 *
	 * @param {string} id
	 * @param {string} mnemonic
	 * @returns {Promise<void>}
	 * @memberof TransactionService
	 */
	public async addSignature(id: string, mnemonic: string): Promise<void> {
		this.assertHasValidIdentifier(id);

		const transaction = await this.#wallet.coin().multiSignature().findById(id);

		const transactionWithSignature = await this.#wallet.coin().transaction().multiSign(transaction, {
			sign: { mnemonic },
		});

		await this.#wallet.coin().multiSignature().broadcast(transactionWithSignature.data());
	}

	/**
	 * Sign a Transfer transaction.
	 *
	 * @param {Contracts.TransferInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signTransfer(input: Contracts.TransferInput, options?: Contracts.TransactionOptions): Promise<string> {
		return this.signTransaction("transfer", input, options);
	}

	/**
	 * Sign a Second-Signature Registration transaction.
	 *
	 * @param {Contracts.SecondSignatureInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signSecondSignature(
		input: Contracts.SecondSignatureInput,
		options?: Contracts.TransactionOptions,
	): Promise<string> {
		return this.signTransaction("secondSignature", input, options);
	}

	/**
	 * Sign a Delegate Registration transaction.
	 *
	 * @param {Contracts.DelegateRegistrationInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signDelegateRegistration(
		input: Contracts.DelegateRegistrationInput,
		options?: Contracts.TransactionOptions,
	): Promise<string> {
		return this.signTransaction("delegateRegistration", input, options);
	}

	/**
	 * Sign a Vote transaction.
	 *
	 * @param {Contracts.VoteInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signVote(input: Contracts.VoteInput, options?: Contracts.TransactionOptions): Promise<string> {
		return this.signTransaction("vote", input, options);
	}

	/**
	 * Sign a Multi-Signature Registration transaction.
	 *
	 * @param {Contracts.MultiSignatureInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signMultiSignature(
		input: Contracts.MultiSignatureInput,
		options?: Contracts.TransactionOptions,
	): Promise<string> {
		return this.signTransaction("multiSignature", input, options);
	}

	/**
	 * Sign an IPFS transaction.
	 *
	 * @param {Contracts.IpfsInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signIpfs(input: Contracts.IpfsInput, options?: Contracts.TransactionOptions): Promise<string> {
		return this.signTransaction("ipfs", input, options);
	}

	/**
	 * Sign a Multi-Payment transaction.
	 *
	 * @param {Contracts.MultiPaymentInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signMultiPayment(
		input: Contracts.MultiPaymentInput,
		options?: Contracts.TransactionOptions,
	): Promise<string> {
		return this.signTransaction("multiPayment", input, options);
	}

	/**
	 * Sign a Delegate Resignation transaction.
	 *
	 * @param {Contracts.DelegateResignationInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signDelegateResignation(
		input: Contracts.DelegateResignationInput,
		options?: Contracts.TransactionOptions,
	): Promise<string> {
		return this.signTransaction("delegateResignation", input, options);
	}

	/**
	 * Sign a HTLC Lock transaction.
	 *
	 * @param {Contracts.HtlcLockInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signHtlcLock(input: Contracts.HtlcLockInput, options?: Contracts.TransactionOptions): Promise<string> {
		return this.signTransaction("htlcLock", input, options);
	}

	/**
	 * Sign a HTLC Claim transaction.
	 *
	 * @param {Contracts.HtlcClaimInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signHtlcClaim(
		input: Contracts.HtlcClaimInput,
		options?: Contracts.TransactionOptions,
	): Promise<string> {
		return this.signTransaction("htlcClaim", input, options);
	}

	/**
	 * Sign a HTLC Refund transaction.
	 *
	 * @param {Contracts.HtlcRefundInput} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	public async signHtlcRefund(
		input: Contracts.HtlcRefundInput,
		options?: Contracts.TransactionOptions,
	): Promise<string> {
		return this.signTransaction("htlcRefund", input, options);
	}

	/**
	 * Get the transaction for the given ID if it is exists with any valid state.
	 *
	 * @param {string} id
	 * @returns {Contracts.SignedTransactionData}
	 * @memberof TransactionService
	 */
	public transaction(id: string): Contracts.SignedTransactionData {
		this.assertHasValidIdentifier(id);

		if (this.hasBeenConfirmed(id)) {
			return this.#confirmed[id];
		}

		if (this.hasBeenBroadcasted(id)) {
			return this.#broadcasted[id];
		}

		if (this.hasBeenSigned(id)) {
			return this.#signed[id];
		}

		if (this.isAwaitingOurSignature(id)) {
			return this.#waitingForOurSignature[id];
		}

		if (this.isAwaitingOtherSignatures(id)) {
			return this.#waitingForOtherSignatures[id];
		}

		throw new Error(`Transaction [${id}] could not be found.`);
	}

	/**
	 * Get all transactions that are pending in some state.
	 *
	 * @returns {SignedTransactionDataDictionary}
	 * @memberof TransactionService
	 */
	public pending(): SignedTransactionDataDictionary {
		return {
			...this.signed(),
			...this.broadcasted(),
			...this.waitingForOtherSignatures(),
			...this.waitingForOurSignature(),
		};
	}

	/**
	 * Get all transactions that have been signed.
	 *
	 * @returns {SignedTransactionDataDictionary}
	 * @memberof TransactionService
	 */
	public signed(): SignedTransactionDataDictionary {
		return this.#signed;
	}

	/**
	 * Get all transactions that have been broadcasted.
	 *
	 * @returns {SignedTransactionDataDictionary}
	 * @memberof TransactionService
	 */
	public broadcasted(): SignedTransactionDataDictionary {
		return this.#broadcasted;
	}

	/**
	 * Get all transactions that are waiting for your signature.
	 *
	 * @returns {SignedTransactionDataDictionary}
	 * @memberof TransactionService
	 */
	public waitingForOurSignature(): SignedTransactionDataDictionary {
		return this.#waitingForOurSignature;
	}

	/**
	 * Get all transactions that are waiting for the signatures of other participants.
	 *
	 * @returns {SignedTransactionDataDictionary}
	 * @memberof TransactionService
	 */
	public waitingForOtherSignatures(): SignedTransactionDataDictionary {
		return this.#waitingForOtherSignatures;
	}

	/**
	 * Check if the given ID has been signed.
	 *
	 * @param {string} id
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public hasBeenSigned(id: string): boolean {
		this.assertHasValidIdentifier(id);

		return this.#signed[id] !== undefined;
	}

	/**
	 * Check if the given ID has been broadcasted.
	 *
	 * @param {string} id
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public hasBeenBroadcasted(id: string): boolean {
		this.assertHasValidIdentifier(id);

		return this.#broadcasted[id] !== undefined;
	}

	/**
	 * Check if the given ID has been confirmed.
	 *
	 * @param {string} id
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public hasBeenConfirmed(id: string): boolean {
		this.assertHasValidIdentifier(id);

		return this.#confirmed[id] !== undefined;
	}

	/**
	 * Check if the given ID is waiting to be confirmed.
	 *
	 * @param {string} id
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public isAwaitingConfirmation(id: string): boolean {
		this.assertHasValidIdentifier(id);

		return this.#broadcasted[id] !== undefined;
	}

	/**
	 * Check if the given ID is waiting for your signature.
	 *
	 * @param {string} id
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public isAwaitingOurSignature(id: string): boolean {
		this.assertHasValidIdentifier(id);

		return this.#waitingForOurSignature[id] !== undefined;
	}

	/**
	 * Check if the given ID is waiting for signatures of other participants.
	 *
	 * @param {string} id
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public isAwaitingOtherSignatures(id: string): boolean {
		this.assertHasValidIdentifier(id);

		return this.#waitingForOtherSignatures[id] !== undefined;
	}

	/**
	 * Check if the given ID is waiting for a signature from the given public key.
	 *
	 * @param {string} id
	 * @param {string} publicKey
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public isAwaitingSignatureByPublicKey(id: string, publicKey: string): boolean {
		this.assertHasValidIdentifier(id);

		let transaction: Contracts.SignedTransactionData | undefined;

		if (this.#waitingForOurSignature[id]) {
			transaction = this.#waitingForOurSignature[id];
		}

		if (this.#waitingForOtherSignatures[id]) {
			transaction = this.#waitingForOtherSignatures[id];
		}

		if (transaction === undefined) {
			throw new Error(`Transaction [${id}] is not awaiting any signatures.`);
		}

		return this.#wallet.coin().multiSignature().needsWalletSignature(transaction, publicKey);
	}

	/**
	 * Check if the given transaction for the given ID can be signed.
	 *
	 * This only affects Multi-Signature (Registration) transactions!
	 *
	 * @param {string} id
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public canBeSigned(id: string): boolean {
		this.assertHasValidIdentifier(id);

		return this.#wallet.coin().multiSignature().needsWalletSignature(this.transaction(id), this.getPublicKey());
	}

	/**
	 * Check if the given transaction for the given ID can be broadcasted.
	 *
	 * This only affects Multi-Signature (Registration) transactions!
	 *
	 * @param {string} id
	 * @returns {boolean}
	 * @memberof TransactionService
	 */
	public canBeBroadcasted(id: string): boolean {
		this.assertHasValidIdentifier(id);

		return this.#signed[id] !== undefined;
	}

	/**
	 * Broadcast the given ID.
	 *
	 * @param {string} id
	 * @returns {Promise<Contracts.BroadcastResponse>}
	 * @memberof TransactionService
	 */
	public async broadcast(id: string): Promise<Contracts.BroadcastResponse> {
		this.assertHasValidIdentifier(id);

		const transaction: Contracts.SignedTransactionData = this.transaction(id);

		let result: Contracts.BroadcastResponse = {
			accepted: [],
			rejected: [],
			errors: {},
		};

		if (this.canBeBroadcasted(id)) {
			if (State.profile().usesMultiPeerBroadcasting()) {
				result = await this.#wallet.client().broadcastSpread([transaction], this.#wallet.getRelays());
			} else {
				result = await this.#wallet.client().broadcast([transaction]);
			}
		} else if (transaction.isMultiSignature() || transaction.isMultiSignatureRegistration()) {
			result.accepted.push(await this.#wallet.coin().multiSignature().broadcast(transaction.data()));
		}

		if (result.accepted.includes(transaction.id())) {
			this.#broadcasted[id] = this.#signed[id];
		}

		return result;
	}

	/**
	 * Check if the given ID has been confirmed by the respective network.
	 *
	 * @param {string} id
	 * @returns {Promise<boolean>}
	 * @memberof TransactionService
	 */
	public async confirm(id: string): Promise<boolean> {
		this.assertHasValidIdentifier(id);

		if (!this.isAwaitingConfirmation(id)) {
			throw new Error(`Transaction [${id}] is not awaiting confirmation.`);
		}

		try {
			const transactionLocal: Contracts.SignedTransactionData = this.transaction(id);
			const transaction: Contracts.TransactionData = await this.#wallet
				.client()
				.transaction(transactionLocal.id());

			if (transaction.isConfirmed()) {
				delete this.#signed[id];
				delete this.#broadcasted[id];
				delete this.#waitingForOtherSignatures[id];
				delete this.#waitingForOurSignature[id];

				// We store the transaction here to be able to access it after it
				// has been confirmed. This list won't be persisted which means
				// it will be gone after a reboot of the consumer application.
				this.#confirmed[id] = transactionLocal;
			}

			return transaction.isConfirmed();
		} catch {
			return false;
		}
	}

	/**
	 * Dump the transactions as JSON strings.
	 *
	 * @memberof TransactionService
	 */
	public dump(): void {
		const dumpStorage = (storage: object, storageKey: string) => {
			const result: Record<string, object> = {};

			for (const [id, transaction] of Object.entries(storage)) {
				this.assertHasValidIdentifier(id);

				result[id] = transaction;
			}

			this.#wallet.data().set(storageKey, result);
		};

		dumpStorage(this.#signed, WalletData.SignedTransactions);
		dumpStorage(this.#broadcasted, WalletData.BroadcastedTransactions);
		dumpStorage(this.#waitingForOurSignature, WalletData.WaitingForOurSignatureTransactions);
		dumpStorage(this.#waitingForOtherSignatures, WalletData.WaitingForOtherSignaturesTransactions);
	}

	/**
	 * Restore the transactions as DTO instances.
	 *
	 * @memberof TransactionService
	 */
	public restore(): void {
		const restoreStorage = (storage: object, storageKey: string) => {
			const transactions: object = this.#wallet.data().get(storageKey) || {};

			for (const [id, transaction] of Object.entries(transactions)) {
				this.assertHasValidIdentifier(id);

				storage[id] = this.#wallet.dataTransferObject().signedTransaction(id, transaction);
			}
		};

		restoreStorage(this.#signed, WalletData.SignedTransactions);
		restoreStorage(this.#broadcasted, WalletData.BroadcastedTransactions);
		restoreStorage(this.#waitingForOurSignature, WalletData.WaitingForOurSignatureTransactions);
		restoreStorage(this.#waitingForOtherSignatures, WalletData.WaitingForOtherSignaturesTransactions);
	}

	/**
	 * Sign a transaction of the given type.
	 *
	 * @private
	 * @param {string} type
	 * @param {*} input
	 * @param {Contracts.TransactionOptions} [options]
	 * @returns {Promise<string>}
	 * @memberof TransactionService
	 */
	private async signTransaction(type: string, input: any, options?: Contracts.TransactionOptions): Promise<string> {
		const transaction: Contracts.SignedTransactionData = await this.#wallet
			.coin()
			.transaction()
			[type](input, options);

		const uuid: string = uuidv4();

		// When we are working with Multi-Signatures we need to sign them in split through
		// broadcasting and fetching them multiple times until all participants have signed
		// the transaction. Once the transaction is fully signed we can mark it as finished.
		if (transaction.isMultiSignature() || transaction.isMultiSignatureRegistration()) {
			this.#waitingForOtherSignatures[uuid] = transaction;
		} else {
			this.#signed[uuid] = transaction;
		}

		return uuid;
	}

	/**
	 * Ensure that the given ID is defined to avoid faulty data access.
	 *
	 * @private
	 * @param {string} id
	 * @memberof TransactionService
	 */
	private assertHasValidIdentifier(id: string): void {
		if (id === undefined) {
			throw new Error("Encountered a malformed ID. This looks like a bug.");
		}
	}

	/**
	 * Get the public key of the current wallet.
	 *
	 * @private
	 * @param {string} id
	 * @memberof TransactionService
	 */
	private getPublicKey(): string {
		const publicKey: string | undefined = this.#wallet.publicKey();

		if (publicKey === undefined) {
			throw new Error(
				"This wallet is lacking a public key. Please sync the wallet before interacting with transactions.",
			);
		}

		return publicKey;
	}

	private async syncPendingMultiSignatures(): Promise<void> {
		const transactions = await this.#wallet.coin().multiSignature().allWithPendingState(this.getPublicKey());

		this.#waitingForOurSignature = {};
		this.#waitingForOtherSignatures = {};

		for (const transaction of transactions) {
			const transactionId: string = transaction.id;
			const signedTransaction = new SignedTransactionData(
				transactionId,
				transaction,
				JSON.stringify(transaction),
			);

			this.#waitingForOurSignature[transactionId] = signedTransaction;
			this.#waitingForOtherSignatures[transactionId] = signedTransaction;

			if (!this.canBeSigned(transactionId)) {
				delete this.#waitingForOurSignature[transactionId];
			}
		}
	}

	private async syncReadyMultiSignatures(): Promise<void> {
		const transactions = await this.#wallet.coin().multiSignature().allWithReadyState(this.getPublicKey());

		for (const transaction of transactions) {
			this.#signed[transaction.id] = new SignedTransactionData(
				transaction.id,
				transaction,
				JSON.stringify(transaction),
			);
		}
	}
}
